apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: tickethub
manifests:
  rawYaml:
    - ./infra/kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: sivam96/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # sync:
      #   infer:
      #     - "src/**/*.ts"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sivam96/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      # sync:
      #   infer:
      #     - "src/**/*.ts"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sivam96/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      # sync:
      #   infer:
      #     - "src/**/*.ts"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sivam96/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      # sync:
      #   infer:
      #     - "src/**/*.ts"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sivam96/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      # sync:
      #   infer:
      #     - "src/**/*.ts"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
