apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: ticket.dev
      http:
        paths:
          # - pathType: Prefix
          #   path: /
          #   backend:
          #     service:
          #       name: auth-serv
          #       port:
          #         number: 8000
          - pathType: Prefix
            path: /api/auth/?(.*)
            backend:
              service:
                name: auth-serv
                port:
                  number: 8000
          - pathType: Prefix
            path: /api/ticket/?(.*)
            backend:
              service:
                name: tickets-serv
                port:
                  number: 8000
