apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc
provisioner: docker.io/hostpath
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  path: /mnt/host/c/k8svolume
