apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    server_name: $POD_NAME
    jetstream {
      store_dir: /data/jetstream
      max_mem: 1G
      max_file: 1G
    }
    cluster {
      port: 6222
      name: $CLUSTER_NAME
      routes: [
        nats://nats-0.nats-svc:6222
        nats://nats-1.nats-svc:6222
        nats://nats-2.nats-svc:6222
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 30
    }
