apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  mongoUrl: "mongodb://mongo-0.mongo-svc.default.svc.cluster.local:27017,mongo-1.mongo-svc.default.svc.cluster.local:27017/auth"
  jwtKey: "auth321"
  cookieKey: "auth456"

