apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 2
  serviceName: "mongo-svc"
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:5.0
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec: 
        resources:
          requests:
            storage: 1Gi
        accessModes: 
          - ReadWriteOnce
        storageClassName: local-sc
