apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  mongoUrl: "mongodb://orders-mongo-0.orders-mongo-svc.default.svc.cluster.local:27017,orders-mongo-1.orders-mongo-svc.default.svc.cluster.local:27017/ticket"
  jwtKey: "auth321"
  cookieKey: "auth456"

